version: "3.8"

services:
  # 🐘 Zookeeper (necessário para Kafka sem KRaft)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - messaging-net

  # 🔌 Kafka Broker com dual listeners
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092" # Porta interna (entre containers)
      - "9093:9093" # Porta externa (para PyCharm via localhost)
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - messaging-net
    volumes:
      - ./kafka-config/server.properties:/etc/kafka/server.properties
      - ./kafka-logs/:/tmp/kafka-logs

  # 🧭 Redpanda Console (interface web)
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8081:8080" # http://localhost:8081
    environment:
      - KAFKA_BROKERS=kafka:9092 # acesso interno ao Kafka
    depends_on:
      - kafka
    networks:
      - messaging-net

networks:
  messaging-net:
    driver: bridge
